#ifndef Entities_Enums_h
#define Entities_Enums_h

enum DataSourceType
{
	NO_DATA_SOURCE = 0,
	COULD_NOT_FIND = 1,
	RANDOM_MISSIONS = 2,
	STORY_MISSIONS = 3,
	MCU = 4,
	WEAPON = 5,
	PLAYER = 6,
	MCUTEMPLATE = 7,
	WEAPONTEMPLATE = 8,
	COMPONENTTEMPLATE = 9,
	ENEMY_MCU = 10,
	BATTLE_RESULT = 11,
	MCU_STATUS = 12
};

enum SquareType
{
	FLAT = 0,
	EMPTY = 1,
	SLOPED_NEG_X = 2,
	SLOPED_POS_X = 3,
	SLOPED_NEG_Z = 4,
	SLOPED_POS_Z = 5,
	CORNER_NEG_X_NEG_Z = 6,
	CORNER_POS_X_NEG_Z = 7,
	CORNER_NEG_X_POS_Z = 8,
	CORNER_POS_X_POS_Z = 9,
	CLIFF_NEG_X = 10,
	CLIFF_POS_X = 11,
	CLIFF_NEG_Z = 12,
	CLIFF_POS_Z = 13,
	CORNER_CLIFF_NEG_X_NEG_Z = 14,
	CORNER_CLIFF_POS_X_NEG_Z = 15,
	CORNER_CLIFF_NEG_X_POS_Z = 16,
	CORNER_CLIFF_POS_X_POS_Z = 17,
	INV_CORNER_NEG_X_NEG_Z = 18,
	INV_CORNER_POS_X_NEG_Z = 19,
	INV_CORNER_NEG_X_POS_Z = 20,
	INV_CORNER_POS_X_POS_Z = 21,
	TRANS_CLIFF_SLOPE_NEG_X = 22,
	TRANS_CLIFF_SLOPE_POS_X = 23,
	TRANS_CLIFF_SLOPE_NEG_Z = 24,
	TRANS_CLIFF_SLOPE_POS_Z = 25,
	TRANS_SLOPE_CLIFF_NEG_X = 26,
	TRANS_SLOPE_CLIFF_POS_X = 27,
	TRANS_SLOPE_CLIFF_NEG_Z = 28,
	TRANS_SLOPE_CLIFF_POS_Z = 29,
	INDETERMINATE = 30
};

enum GridSquareLocation
{
	MIDDLE = 0,
	POS_X_EDGE = 1,
	POS_Z_EDGE = 2,
	POS_X_POS_Z_EDGE = 3
};

enum TerrainChange
{
	TC_NOT_SET = 0,
	TC_NO_CHANGE = 1,
	TC_LOWERING = 2,
	TC_RAISING = 3
};

#endif